version: '2'
services:
    
    pg:
        image: postgres:9.6.1
        container_name: sgg-dev-pg
        ports:
            - "5432:5432"
        volumes:
            - ".data/pg:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: 19216801
            POSTGRES_DB: sgg
            POSTGRES_USER: sgg 
            POSTGRES_INITDB_ARGS: -A trust
    
    redis:
        image: redis:3-alpine
        container_name: sgg-dev-redis
        command: redis-server --appendonly yes
        ports:
            - "6379:6379"
        volumes:
            - ".data/redis:/data"

    influxdb:
        image: influxdb:1.1.0-alpine
        container_name: sgg-dev-influx
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - ".data/i:/data"

    nats:
        image: nats:0.9.4
        container_name: sgg-dev-nats
        ports:
            - "4222:4222"
            - "8222:8222"
