version: '2'
services:
    
    pg:
        image: postgres:9.5
        container_name: sgg-dev-pg
        ports:
            - "5432:5432"
        volumes:
            - ".data/pg:/var/lib/postresql/data"
        environment:
            POSTGRES_PASSWORD: 19216801
            POSTGRES_DB: sgg
            POSTGRES_USER: sgg 
            POSTGRES_INITDB_ARGS: -A trust
    
    redis:
        image: redis:3-alpine
        container_name: sgg-dev-redis
        ports:
            - "6379:6379"
        volumes:
            - ".data/redis:/data"

    rethink:
        image: rethinkdb:2
        container_name: sgg-dev-rethink
        ports:
            - "8080:8080"
            - "28015:28015"
        volumes:
            - ".data/r:/data"

    influxdb:
        image: tutum/influxdb:0.12
        container_name: sgg-dev-influx
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - ".data/i:/data"

    nats:
        image: nats
        container_name: sgg-dev-nats
        ports:
            - "4222:4222"
            - "8222:8222"
