[self]
env = "local"
session_cookie = "space"

[validation]
username_length = 30
disallowed_slugs = [ "admin", "global-mod", "moderator", "adminstrator", "adm", "operator", "root" ]
password_length = 8
