[cache]
backend = "redis"

	[cache.TTL]
	comment = 86400
	user = 3600
	save = 86400
	session = 604800

    [cache.redis]
    addr = "localhost:6379"

[self]
env = "local"

[validation]
username_length = 30
disallowed_slugs = [ "admin", "global-mod", "moderator", "adminstrator", "adm", "operator" ]
password_length = 8
