[cache]
backend = "redis"

	[cache.TTL]
	comment = 86400
	user = 3600
	save = 86400
	session = 604800

    [cache.redis]
    addr = "localhost:6379"

[self]
env = "local"
signing_key = "71cbRVP7CvlSzlJJYkDTDhAdDvZw6KyMKFLEilY9R8ga0EqrqH8ZUEp3Oczry3YfVVcAGhtilaVsbX812FW5vKlc0gfc6U8W"
session_cookie = "space"

[csrf]
signing_key = "m5qcvnGwwSK9Mzh2fQiCkNV3T1IJXkRodW596q7w6TBYKuFbtENQtJaUd6TRwGouTZOP5o55UT1CMYlp9mkhvdgCyJm7uZMu"

[validation]
username_length = 30
disallowed_slugs = [ "admin", "global-mod", "moderator", "adminstrator", "adm", "operator" ]
password_length = 8
